blogs/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy

from blogs.views import home_view, blog_view, about_view, post_view, custom_login_view, register_view, CreateBlogView, \
    profile_view, change_password_view, activate_account, contact_view


urlpatterns = [
    path('', home_view, name='main'),
    path('blogs', blog_view, name='blogs'),
    path('about', about_view, name='about'),
    path('blog/<str:slug>', post_view, name='post_detail'),
    path('login', custom_login_view, name='login'),
    path('logout', LogoutView.as_view(next_page=reverse_lazy('main')), name='logout'),
    path('signup', register_view, name='register'),
    path('activate/<str:uidb64>/<str:token>/', activate_account, name='activate'),
    path('add', CreateBlogView.as_view(), name='add'),
    path('profile', profile_view, name='profile'),
    path('change_password', change_password_view, name='change_password'),
    path('contact', contact_view, name='contact')
    ]

root/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from root import settings

admin.site.site_header = "Admin Panelga Kirish"
admin.site.site_title = "Admin Portali"
admin.site.index_title = "Welcome to UMSRA Researcher Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractUser
from django.db.models import CASCADE, Model, TextField, ForeignKey, EmailField, CharField, SlugField, DateTimeField, \
    ManyToManyField, BooleanField, IntegerField, TextChoices, ImageField
from django.utils.text import slugify
from django_resized import ResizedImageField


class Category(Model):
    name = CharField(max_length=255)
    image = ResizedImageField(upload_to='category/')
    slug = SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        while Category.objects.filter(slug=self.slug).exists():
            slug = Category.objects.filter(slug=self.slug).first().slug
            if '-' in slug:
                try:
                    if slug.split('-')[-1] in self.name:
                        self.slug += '-1'
                    else:
                        self.slug = '-'.join(slug.split('-')[:-1]) + '-' + str(int(slug.split('-')[-1]) + 1)
                except:
                    self.slug = slug + '-1'
            else:
                self.slug += '-1'

        super().save(*args, **kwargs)


class User(AbstractUser):
    # name = CharField(max_length=255)
    email = EmailField(max_length=300)
    phone = CharField(max_length=200)
    bio = TextField(null=True, blank=True)
    image = ImageField(upload_to='user/', default='profile/user.png')
    # password = CharField(max_length=400)
    is_active = BooleanField(default=False)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username


class Blog(Model):
    class Status(TextChoices):
        PENDING = 'pending', 'Pending'
        ACTIVE = 'active', 'Active'
        CANCEL = 'cancel', 'Cancel'
    title = CharField(max_length=300)
    description = RichTextField()
    image = ResizedImageField(upload_to='blogs/%m')
    user = ForeignKey(User, CASCADE, null=False)
    category = ManyToManyField(Category)
    view = IntegerField(default=0)
    status = CharField(max_length=25, choices=Status.choices, default=Status.PENDING)
    created_at = DateTimeField(auto_now=True)
    slug = SlugField(max_length=300, unique=True)

    class Meta:
        db_table = 'blog'
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        while Category.objects.filter(slug=self.slug).exists():
            slug = Category.objects.filter(slug=self.slug).first().slug
            if '-' in slug:
                try:
                    if slug.split('-')[-1] in self.title:
                        self.slug += '-1'
                    else:
                        self.slug = '-'.join(slug.split('-')[:-1]) + '-' + str(int(slug.split('-')[-1]) + 1)
                except:
                    self.slug = slug + '-1'
            else:
                self.slug += '-1'

        super().save(*args, **kwargs)


class Comment(Model):
    text = TextField()
    user = ForeignKey(User, CASCADE, null=False)
    blog = ForeignKey(Blog, CASCADE, related_name='blog_comment')

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return self.text


class AboutUs(Model):
    about = TextField()
    phone = CharField(max_length=50)
    address = CharField(max_length=300)
    email = EmailField(max_length=300)

    class Meta:
        verbose_name = 'AboutUs'
        verbose_name_plural = 'AboutUs'


class ContactMessage(Model):
    name = CharField(max_length=100)
    email = EmailField()
    website = CharField(max_length=100, blank=True, null=True)
    message = TextField()

blogs/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import make_password
from django.forms import ModelForm, Form, CharField, EmailField, Textarea
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from blogs.models import User, Blog
from django import forms


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'description', 'image', 'category']


class LoginForm(AuthenticationForm):
    pass


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    def clean_password(self):
        password = self.data.get('password1')
        print(self.data)
        confirm_password = self.data.get('password2')
        if password != confirm_password:
            print('password error')
            raise forms.ValidationError('Check your password')
        return make_password(password)

    class Meta:
        model = User
        fields = ['username', 'email', 'phone', 'password1']


class ProfileForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'phone', 'bio', 'image']


class ChangePasswordForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['password']


class ContactForm(Form):
    name = CharField(max_length=100)
    email = EmailField()
    website = CharField(required=False)
    message = CharField(widget=Textarea)

blogs/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.sites.shortcuts import get_current_site
from django.views.generic import View
from django.core.mail import EmailMessage
from blogs.forms import LoginForm, RegisterForm, ProfileForm, ChangePasswordForm, BlogForm, ContactForm
from blogs.models import Blog, Category, User, AboutUs, ContactMessage
from django.contrib.auth import login, update_session_auth_hash
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.utils.safestring import mark_safe
from .tokens import account_activation_token


def activate_account(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = get_user_model().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
        user = None

    if user is not None:
        user.is_active = True
        user.save()
        login(request, user)
        return render(request, 'auth/account_activation_success.html')
    else:
        return render(request, 'auth/account_activation_failure.html')


def home_view(request):
    queryset = Blog.objects.filter(status='active').order_by('-created_at')[1:]
    last_post = Blog.objects.filter(status='active').last()
    categories = Category.objects.all()

    context = {
        'blog_list': queryset,
        'last': last_post,
        'categories': categories,
    }

    return render(request, 'blogs/index.html', context)


def blog_view(request):
    queryset = Blog.objects.filter(status='active').order_by('-created_at')
    slug = request.GET.get('category')
    qs = queryset.filter(category__slug=slug) if slug else queryset

    context = {
        'posts': qs,
        'trending_posts': Blog.objects.order_by('-created_at'),
        'category_slug': Category.objects.filter(slug=slug).first(),
        'categories': Category.objects.all(),
    }

    return render(request, 'blogs/blog-category.html', context)


def about_view(request):
    about_us = AboutUs.objects.first()

    context = {
        'about': about_us,
    }

    return render(request, 'blogs/about.html', context)


def post_view(request, slug):
    post = Blog.objects.get(slug=slug)
    categories = Category.objects.filter(blog=post)
    users = User.objects.all()

    context = {
        'post': mark_safe(post),
        'categories': categories,
        'user': users,
    }

    return render(request, 'blogs/post.html', context)


def custom_login_view(request):
    form_class = LoginForm
    template_name = 'auth/login.html'
    next_page = reverse_lazy('main')

    login_view = LoginView.as_view(form_class=form_class, template_name=template_name, success_url=next_page)

    return login_view(request)


def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('auth/confirm_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.content_subtype = 'html'
            email.send()

            return render(request, 'auth/registration_confirmation.html')
        else:
            print(form.errors)
    else:
        form = RegisterForm()

    return render(request, 'auth/register.html', {'form': form})


def about_view(request):
    template_name = 'blogs/about.html'
    context = {'about': AboutUs.objects.first()}

    return render(request, template_name, context)


def post_view(request, slug):
    template_name = 'blogs/post.html'
    post = Blog.objects.get(slug=slug)
    categories = Category.objects.filter(blog=post)
    users = User.objects.all()

    context = {
        'post': post,
        'categories': categories,
        'user': users,
    }

    return render(request, template_name, context)


def profile_view(request):
    template_name = 'profile/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('profile')

    user = request.user

    if request.method == 'POST':
        form = form_class(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect(success_url)
    else:
        form = form_class(instance=user)

    context = {'object': user, 'form': form}

    return render(request, template_name, context)


def change_password_view(request):
    template_name = 'profile/change_password.html'
    form_class = ChangePasswordForm
    success_url = reverse_lazy('profile')

    user = request.user

    if request.method == 'POST':
        form = form_class(user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)  # Обновить хеш сессии, чтобы пользователь не был разлогинен
            return redirect(success_url)
    else:
        form = form_class(user)

    context = {'form': form}

    return render(request, template_name, context)


class CreateBlogView(View):
    template_name = 'blogs/add-post.html'

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        form = BlogForm()
        return render(request, self.template_name, {'form': form, 'categories': categories})

    def post(self, request, *args, **kwargs):
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.user = request.user
            blog.save()
            form.save_m2m()
            return redirect('main')
        else:
            print(form.errors)
            categories = Category.objects.all()
            return render(request, self.template_name, {'form': form, 'categories': categories})


def contact_view(request):
    template_name = 'blogs/contact.html'
    about = AboutUs.objects.first()
    # success_page = reverse_lazy('main')

    context = {
        'about': about
    }

    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact_message = ContactMessage(
                name = form.cleaned_data['name'],
                email = form.cleaned_data['email'],
                website = form.cleaned_data['website'],
                message = form.cleaned_data['message']
            )
            contact_message.save()

            messages.success(request, 'Your message was sent successfully')

            return redirect('contact')
        else:
            form = ContactForm()


    return render(request, template_name, context)

templates/blogs/blog-category.html
{% extends 'blogs/base.html' %}
{% load static %}

{% block title %}Blogs{% endblock title %}

{% block content %}
    <body>
    <!-- pre loader -->
    <div id="load">
        <div class="load__content">
            <div class="load__icon"><img src="{% static 'blogs/assets/images/icons/load.gif' %}" alt="Loading icon"/>
            </div>
        </div>
    </div>
    <!--Nav bar -->
    <!-- main content starts here -->
    <div class="no-pd" id="content">
        <div class="container">
            <div class="breadcrumb">
                <ul>
                    <li><a href="{% url 'main' %}"> <i class="fas fa-home"></i>Home</a></li>
                    <li><a href="{% url 'blogs' %}">Blog</a></li>
                    <li class="active"><a href="#">Category</a></li>
                </ul>
            </div>
            <div class="category">
                <div class="row">
                    <div class="col-12 col-md-5 col-lg-4 order-md-2">
                        <div class="blog-sidebar">
                            <div class="blog-sidebar-section -category">
                                <div class="center-line-title">
                                    <h5>Categories</h5>
                                </div>
                                <!--Category 1::Background Image size is 340 x 80   -->
                                {% for category in categories %}
                                    <a class="category -bar " href="{% url 'blogs' %}?category={{ category.slug }}">
                                        <div class="category__background"
                                             style="background-image: url({{ category.image.url }})"></div>
                                        <h5 class="title">{{ category.name }}</h5>
                                        <h5 class="quantity">{{ category.blog_set.count }}</h5></a>
                                {% endfor %}
                            </div>
                            <div class="blog-sidebar-section -trending-post">
                                <div class="center-line-title">
                                    <h5>Trending post</h5>
                                </div>
                                <!--Trending Post 1 -->
                                {% for trending_post in trending_posts|slice:5 %}
                                    <div class="trending-post">
                                    <div class="trending-post_image">
                                        <div class="rank">{{ forloop.counter }}</div>
                                        <!--Img size is 100 x 100 -->
                                        <img src="{{ trending_post.image.url }}"/>
                                    </div>
                                    <div class="trending-post_content">
                                        <!-- Category Header -->
                                        <h5>{{ trending_post.category.first }}</h5>
                                        <a href="{% url 'post_detail' trending_post.slug %}">{{ trending_post.title }}</a>
                                        <div class="info__time"><i class="far fa-clock"></i>
                                            <p>{{ trending_post.created_at }}</p>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-md-7 col-lg-8 order-md-1">
                        {% if category_slug %}
                            <div class="category__header">
                                <div class="category__header__text">
                                    <h5>Categories:</h5>
                                    <a href="">{{ category_slug.name }}</a>
                                </div>
                                <div class="category__header__filter">
                                </div>
                            </div>
                        {% endif %}
                        <div class="category_content"></div>
                        <div class="col-12">
                            {% for post in posts %}
                                <div class="post-card -small -horizontal">
                                    <a class="card__cover" href="{% url 'post_detail' post.slug %}" tabindex="0"><img
                                            src="{{ post.image.url }}" alt=""></a>
                                    <div class="card__content">
                                        <h5 class="card__content-category">{{ post.category.first }}</h5>
                                        <a class="card__content-title" href="{% url 'post_detail' post.slug %}"
                                           tabindex="0">{{ post.title }}</a>
                                        <div class="card__content-info">
                                            <div class="info__time"><i class="far fa-clock"></i>
                                                <p>{{ post.created_at }}</p>
                                            </div>
                                            <div class="info__comment"><i class="far fa-comment"></i>
                                                <p>{{ post.comment_set.count }}</p>
                                            </div>
                                        </div>
                                        <p class="card__content-description">{{ post.description|striptags|truncatechars:120 }}</p>
                                    </div>
                                </div>
                                <br><br>
                            {% endfor %}
                        </div>
                        <!-- <div class="pagination">
                            <ul>
                                <li class="active"><a href="javascript:void(0)">1</a></li>
                                <li class="pagination__page-number"><a href="javascript:void(0)">2</a></li>
                                <li class="pagination__page-number"><a href="javascript:void(0)">3</a></li>
                                <li><a class="next" href="javascript:void(0)">></a></li>
                            </ul>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer starts Here -->
    </div>
    </body>
{% endblock content %}

templates/blogs/index.html
{% extends 'blogs/base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
    <body>
    <div id="load">
        <div class="load__content">
            <div class="load__icon"><img src="{% static 'blogs/assets/images/icons/load.gif' %}" alt="Loading icon"/>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="container">
            <div class="blog-with-sidebar">
                <div class="row">
                    <div class="col-12 col-md-5 col-lg-4 order-md-2">
                        <div class="blog-sidebar">
                            <div class="blog-sidebar-section -category">
                                <div class="center-line-title">
                                    <h5>Categories</h5>
                                </div>
                                {% for category in categories %}
                                    <a class="category -bar " href="{% url 'blogs' %}?category={{ category.slug }}">
                                        <div class="category__background"
                                             style="background-image: url({{ category.image.url }})"></div>
                                        <h5 class="title">{{ category.name }}</h5>
                                        <h5 class="quantity">{{ category.blog_set.count }}</h5></a>
                                {% endfor %}
                            </div>
                            </a>
                            <div class="blog-sidebar-section -trending-post">
                                <div class="center-line-title">
                                    <h5>Trending post</h5>
                                </div>

                                {% for blog in blog_list|slice:5 %}
                                    <div class="trending-post">
                                        <div class="trending-post_image">
                                            <div class="rank">{{ forloop.counter }}</div>
                                            <!--Img size is 100 x 100 -->
                                            <img src="{{ blog.image.url }}"/>
                                        </div>
                                        <div class="trending-post_content">
                                            <!-- Category Header -->
                                            <h5>{{ blog.category.first }}</h5>
                                            <a href="{% url 'post_detail' blog.slug %}">{{ blog.title }}</a>
                                            <div class="info__time"><i class="far fa-clock"></i>
                                                <p>{{ blog.created_at }}</p>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <!-- Subscribe Form -->
                            {#                        <form class="subcribe-box subcribe-box" action="/" method="POST">#}
                            {#                            <h5>Subcribe</h5>#}
                            {#                            <p>Lorem ipsum dolor amet, consectetur adipiscing elit, sed tempor.</p>#}
                            {#                            <input placeholder="Your email" name="email" type="email"/>#}
                            {#                            <a class="btn -normal" href="#">Subcribe</a>#}
                            {#                        </form>#}
                        </div>
                    </div>
                    <!--- End of Right Side Bar ----->

                    <div class="col-12 col-md-7 col-lg-8 order-md-1">
                        <div class="row">
                            <div class="col-sm-6 col-md-12">
                                <div class="post-card -full -center">
                                    <a class="card__cover" href="{% url 'post_detail' last.slug %}">
                                        <img src="{{ last.image.url }}"
                                             alt="Getting started with DevOps automation"/>
                                    </a>
                                    <div class="card__content">
                                        <h5 class="card__content-category">{{ last.category.first }}</h5>
                                        <a class="card__content-title"
                                           href="{% url 'post_detail' last.slug %}">{{ last.title }}</a>
                                        <div class="card__content-info">
                                            <div class="info__time info__author"><i class="far fa-user"></i>
                                                <p>{{ last.user.username }}</p>
                                            </div>
                                            <div class="info__time"><i class="far fa-clock"></i>
                                                <p>{{ last.created_at }}</p>
                                            </div>
                                            <div class="info__comment"><i class="far fa-comment"></i>
                                                <p>{{ last.blog_comment_set.count }}</p>
                                            </div>
                                        </div>
                                        <p class="card__content-description">{{ last.description|safe|truncatechars:145 }}</p>
                                        <a class="more-btn" href="{% url 'post_detail' last.slug %}">Read more </a>
                                    </div>
                                </div>
                            </div>
                            <div class="news-block__content -default">
                                <div class="news-block__content__slide">
                                    <div class="row">
                                        <div class="col-12">
                                        </div>
                                        <div class="col-12">
                                            <div class="row">
                                                {% for blog in blog_list %}
                                                    <div class="col-12 col-sm-6">
                                                        <div class="post-card -small">
                                                            <a class="card__cover"
                                                               href="{% url 'post_detail' blog.slug %}">
                                                                <img src="{{ blog.image.url }}"/></a>
                                                            <div class="card__content">
                                                                <h5 class="card__content-category">{{ blog.category.first }}</h5>
                                                                <a class="card__content-title"
                                                                   href="{% url 'post_detail' blog.slug %}">{{ blog.title }}</a>
                                                                <div class="card__content-info">
                                                                    <div class="info__time"><i class="far fa-clock"></i>
                                                                        <p>{{ blog.created_at }}</p>
                                                                    </div>
                                                                    <div class="info__comment"><i
                                                                            class="far fa-comment"></i>
                                                                        <p>{{ blog.blog_comment_set.count }}</p>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    </body>
{% endblock content %}
{#Lorem ipsum dolor sit amet, consectetur adipisicing elit. #}
{#Adipisci aspernatur assumenda aut culpa, doloremque dolorum, #}
{#earum est ipsum nobis possimus quia quibusdam quisquam quos,#}
{#ratione recusandae similique sint soluta unde.#}